---
driver:
  name: vagrant
  vm_hostname: 'mysql.local'

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: sbeliakou/centos-7.3-x86_64-minimal

suites:
  - name: default
    run_list:
      - recipe[task3_database::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
